=== caveman2cosmos/Caveman2Cosmos/Assets/XML/Schema/Civ4GameText.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.firaxis.com" elementFormDefault="qualified" targetNamespace="http://www.firaxis.com">
  <xs:element name="Civ4GameText">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="TEXT" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:all>
              <xs:element ref="Tag"/>
              <xs:element name="English" type="Gametext"/>
              <xs:element name="French" type="Gametext" minOccurs="0"/>
              <xs:element name="German" type="Gametext" minOccurs="0"/>
              <xs:element name="Italian" type="Gametext" minOccurs="0"/>
              <xs:element name="Spanish" type="Gametext" minOccurs="0"/>
              <xs:element name="Polish" type="Gametext" minOccurs="0"/>
              <xs:element name="Russian" type="Gametext" minOccurs="0"/>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Tag">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="TXT_[\c-[:]]*|AI_DIPLO_[\c-[:]]*|USER_DIPLO_[\c-[:]]*|INTERFACE_[\c-[:]]*"/>
        <xs:whiteSpace value="collapse"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:complexType mixed="true" name="Gametext">
    <xs:all>
      <xs:element name="Text" type="xs:string" minOccurs="0"/>
      <xs:element name="Gender" type="xs:NMTOKEN" minOccurs="0"/>
      <xs:element name="Plural" type="xs:NMTOKEN" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
</xs:schema>

=== caveman2cosmos/Caveman2Cosmos/Assets/XML/Text/Alt_Timelines/Cyberpunk/CyberPunk_Building_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CYBERPUNK_EMBASSY</Tag>
		<English>Culture (Cyberpunk)</English>
		<Polish>Kultura (Cyberpunk)</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CYBERPUNK_EMBASSY_PEDIA</Tag>
		<English>Cyberpunk is a postmodern science fiction genre noted for its focus on "high tech and low life." It features advanced science, such as information technology and cybernetics, coupled with a degree of breakdown or radical change in the social order. Cyberpunk plots often center on a conflict among hackers, artificial intelligences, and megacorporations, and tend to be set in a near-future Earth, rather than the far-future settings or galactic vistas found in novels such as Isaac Asimov's Foundation or Frank Herbert's Dune. The settings are usually post-industrial dystopias but tend to be marked by extraordinary cultural ferment and the use of technology in ways never anticipated by its creators ("the street finds its own uses for things"). Much of the genre's atmosphere echoes film noir, and written works in the genre often use techniques from detective fiction.</English>
		<Polish>Cyberpunk - nurt w literaturze science-fiction oraz kinematografii, który skupia się na ludziach i otaczającej ich zaawansowanej technologii komputerowej i informacyjnej, niekiedy połączony z różnego rodzaju zamieszaniem w społeczeństwie (np. stan wojenny). Pojęcie cyberpunku można rozważać również pod kątem postawy życiowej, filozofii lub ideologii, w tym wypadku pojęcie cyberpunku jest rozważane bardziej pod kątem porównywania człowieka z maszyną (cybernetyka) i wynikających z tego pytań na temat duszy, Boga oraz świadomości.</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CYBERPUNK_EMBASSY_STRATEGY</Tag>
		<English>Build Culture (Cyberpunk) to gain access to unique buildings and units.</English>
		<French>Construire la culture (Cyberpunk) pour avoir accès à des bâtiments et unités uniques.</French>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CYBER_INSECT_LAB</Tag>
		<English>Cyber Insect Lab</English>
		<French>Laboratoire de Cyber-Insectes</French>
		<Polish>Laboratorium Cyberowadów</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CYBER_INSECT_LAB_PEDIA</Tag>
		<English>Implanted microchips in insects allow to remote control them and use them as spies and soldiers.</English>
		<Polish>Sterowane przez komputer owady tworzone są w tym ośrodku badawczym.</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CYBER_INSECT_LAB_STRATEGY</Tag>
		<English>Build a Cyber Insect Lab to increase your cities Science.</English>
		<French>Construisez un [COLOR_BUILDING_TEXT]Laboratoire de Cyber-Insectes[COLOR_REVERT] pour augmenter la Science de votre ville.</French>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_DREAM_ARTIST</Tag>
		<English>Dream Artist</English>
		<French>Artiste des rêves</French>
		<Polish>Artysta Snu</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_DREAM_ARTIST_PEDIA</Tag>
		<English>A Dream Artist is a designer of wonderfull dreams for Dream Simulation Centers.</English>
		<Polish>Projektant i twórca artystycznych snów.</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_DREAM_ARTIST_STRATEGY</Tag>
		<English>Build a Dream Artist to increase your cities Gold.</English>
		<French>Construisez un [COLOR_BUILDING_TEXT]Artiste des rêves[COLOR_REVERT] pour accroître les revenus de la ville.</French>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_DREAM_PROPAGANDA</Tag>
		<English>Dream Propaganda</English>
		<French>Propagande des Rêves</French>
		<Polish>Propaganda Snu</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_DREAM_PROPAGANDA_PEDIA</Tag>
		<English>While dreaming in a Dream Simulation Center, the people are influenced with propaganda and commercials.</English>
		<Polish>Ludzie w czasie snu są atakowani propagandowymi przekazami i sloganami.</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_DREAM_PROPAGANDA_STRATEGY</Tag>
		<English>Build an Dream Propaganda to increase your cities Espionage.</English>
		<French>Construire une [COLOR_BUILDING_TEXT]Propagande des Rêves[COLOR_REVERT] vous permettra d'améliorer l'espionnage au sein de vos villes.</French>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_DREAM_SIMULATION_CENTER</Tag>
		<English>Dream Simulation Center</English>
		<French>Centre de Simulation de rêves</French>
		<Polish>Centrum Symulacji Snu</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_DREAM_SIMULATION_CENTER_PEDIA</Tag>
		<English>People can go into Dream Simulation Centers to have their sleep simulated. This way, they only need 2 hours of "sleep" instead of 8 hours, but at the cost of headaches and other health problems.</English>
		<Polish>Miejsce w którym ludzi za opłatą śnią dowolne sny.</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_DREAM_SIMULATION_CENTER_STRATEGY</Tag>
		<English>Build an Dream Simulation Center to increase your cities Science.</English>
		<French>Construisez un [COLOR_BUILDING_TEXT]Centre de Simulation des Rêves[COLOR_REVERT] pour augmenter la Science de votre ville.</French>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_INSECT_MANIPULATION_LAB</Tag>
		<English>Insect Manipulation Lab</English>
		<French>Laboratoire de Manipulation d'Insectes</French>
		<Polish>Laboratorium Manipulacji Owadami</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_INSECT_MANIPULATION_LAB_PEDIA</Tag>
		<English>Scientists try to manipulate insects to use them against their enemies as spies or soldiers.</English>
		<Polish>Naukowcy eksperymentują na owadami by skłonić je do walki z wrogami Twojego imperium.</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_INSECT_MANIPULATION_LAB_STRATEGY</Tag>
		<English>Build an Insect Manipulation Lab to get access to controlled insect units.</English>
		<French>Construire un [COLOR_BUILDING_TEXT]Laboratoire de Manipulation d'Insectes[COLOR_REVERT] pour avoir accès à des unités d'insectes contrôlés.</French>
	</TEXT>
</Civ4GameText>

=== caveman2cosmos/Caveman2Cosmos/Assets/XML/GameText/Subdue_Animals_Combat_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_UNITCOMBAT_ANIMAL</Tag>
		<English>Animals</English>
		<French>Unités animales</French>
		<German>Tiereinheiten</German>
		<Italian>Animali</Italian>
		<Spanish>Animales</Spanish>
		<Polish>Zwierzęta</Polish>
		<Russian>Æèâîòíûå</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNITCOMBAT_HUNTER</Tag>
		<English>Hunters</English>
		<French>Chasseurs</French>
		<Italian>Cacciatori</Italian>
		<German>Jäger</German>
		<Polish>Łowcy</Polish>
		<Russian>Îõîòíèêè</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNITCOMBAT_SEA_ANIMAL</Tag>
		<English>Sea Animals</English>
		<French>Unités animales marines</French>
		<German>Meerestiereinheiten</German>
		<Italian>Animali marini</Italian>
		<Spanish>Animales</Spanish>
		<Polish>Zwierzęta Morskie</Polish>
		<Russian>Ðûáû</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNITCOMBAT_SEA_ANIMAL_TALES</Tag>
		<English>Sea Animals (Tales)</English>
		<French>Animaux marins (Histoires)</French>
		<German>Meerestiereinheiten (Geschichten)</German>
		<Italian>Animali marini (Storie)</Italian>
		<Spanish>Sea Animales</Spanish>
		<Polish>Zwierzęta Morskie (Opowieści)</Polish>
		<Russian>Ñêàçû î ðûáàõ</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNITCOMBAT_SEA_LARGE</Tag>
		<English>Sea Animals (Large)</English>
		<French>Grands animaux marins</French>
		<German>Große Meerestiereinheiten</German>
		<Italian>Animali marini (Grandi)</Italian>
		<Spanish>Sea Animales</Spanish>
		<Polish>Zwierzęta Morskie (Wielkie)</Polish>
		<Russian>Ìåëêèå ðûáû</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNITCOMBAT_SEA_SMALL</Tag>
		<English>Sea Animals (Small)</English>
		<French>Petits animaux marins</French>
		<German>Kleine Meerestiereinheiten</German>
		<Italian>Animali marini (Piccoli)</Italian>
		<Spanish>Sea Animales</Spanish>
		<Polish>Zwierzęta Morskie (Małe)</Polish>
		<Russian>Áîëüøèå ðûáû</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNITCOMBAT_WHALE</Tag>
		<English>Whale</English>
		<French>Baleine</French>
		<Italian>Balene</Italian>
		<German>Wal</German>
		<Polish>Wieloryb</Polish>
		<Russian>Êèòû</Russian>
	</TEXT>
</Civ4GameText>

=== caveman2cosmos/Caveman2Cosmos/Assets/Modules/My_Mods (unloaded)/Antiquities (broken)/AutoBuild_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CAVE_IN_NATION</Tag>
		<English>Cave in the nation</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CAVE_NEAR_CITY</Tag>
		<English>Cave in the vicinity</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_ELITE_HOUSING</Tag>
		<English>Housing - Elite</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_ELITE_HOUSING_PEDIA</Tag>
		<English>Game auto builds used to identify when a city has elite housing that can support more secialised buildings.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_NEAR_CITY_STUFF_PEDIA</Tag>
		<English>Game auto builds used to identify when a bonus or resource is somewhere in the nation but not in the vicinity of this city.</English>
	</TEXT>
</Civ4GameText>

=== caveman2cosmos/Caveman2Cosmos/Assets/XML/GameText/Modules/Alt_Timelines/Megafauna_Units/Mammoths/Mammoths_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_BUILDING_MAMMOTH_HERD</Tag>
		<English>Herd (Mammoth)</English>
		<French>
			<Text>Troupeau de Mammouth</Text>
			<Gender>Male</Gender>
			<Plural>0</Plural>
		</French>
		<Italian>
			<Text>Branco - Mammut</Text>
			<Gender>Male</Gender>
			<Plural>0</Plural>
		</Italian>
		<Polish>Stado - Mamuty</Polish>
		<Russian>Òàáóí ìàìîíòîâ</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_MAMMOTH_HERD_PEDIA</Tag>
		<English>Only subdued mammoth can build the mammoth herd. It provides a mammoth resource. There can only be one per civ.</English>
		<Italian>Solo i mammut addomesticati possono costruire il Branco - Mammut; fornisce una risorsa di mammut.</Italian>
		<Polish>Mamut włochaty należał do ulubionej zwierzyny łownej człowieka w późnym plejstocenie, co znalazło swe odzwierciedlenie w zachowanych do dzisiaj licznych wyobrażeniach i malowidłach, pozostawionych głównie na ścianach jaskiń (np. w Rouffignac we Francji). Mamuty były źródłem pożywienia, ale dostarczały także materiałów do wyrobu okryć (skóry), sprzętów domowych, narzędzi i ozdób (kości, ciosy). Kości wykorzystywane były sporadycznie również do budowy paleolitycznych domostw, czego ślady odnaleziono w miejscowości Meziriczi na Ukrainie.</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_MAMMOTH_TRAINER_EFFECT</Tag>
		<English>Effect - Heritage - Mammoths</English>
		<French>Effet - Patrimoine (Mammouth)</French>
		<Polish>Efekt - Dziedzictwo - Mamut</Polish>
		<Russian>Ïèòîìíèê ìàìîíòîâ</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_MAMMOTH_TRAINER_HERITAGE</Tag>
		<English>Heritage - Mammoth</English>
		<French>Patrimoine (Mammouth)</French>
		<Polish>Dziedzictwo - Mamut</Polish>
		<Russian>Ðàçâåäåíèå ìàìîíòîâ</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_MAMMOTH_TRAINER_HERITAGE_PEDIA</Tag>
		<English>Instead of only being able to train Mammoth units in the city you built the wonder in this building allows them to be built in any of your cities. It can only be built in the ciy with the Mammothr Trainer World Wonder.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_MAMMOTH_TRAINER_PEDIA</Tag>
		<English>The woolly mammoth was the last species of the genus. Most populations of the woolly mammoth in North America and Eurasia, as well all the Columbian mammoths in North America, died out around the time of the last glacial retreat, as part of a mass extinction of megafauna in northern Eurasia and the Americas.</English>
		<Italian>Il mammut peloso fu l'ultima specie del suo genere. La maggior parte dei mammut pelosi del Nordamerica e dell'Eurasia morirono surante l'ultima era glaciale, facendo parte di un'estinzione di massa della megafauna nell'emisfero settentrionale.</Italian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_MAMMOTH_TRAINER</Tag>
		<English>Animal Trainer (Mammoth)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_BALLISTA_MAMMOTH</Tag>
		<English>Ballista Mammoth</English>
		<French>
			<Text>Mammouth Balliste</Text>
			<Gender>Male</Gender>
			<Plural>0</Plural>
		</French>
		<Italian>Mammut con balista</Italian>
		<Polish>Mamut-Ballista</Polish>
		<Russian>Ìàìîíò ñ áàëëèñòîé</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_BALLISTA_MAMMOTH_PEDIA</Tag>
		<English>Great mammoths walk in northern tundras, some tribes hunt them for meat, skins and bones. But some hunt them them for beast of war. Capturing one alive and bending is no easy task, but if succeeded. Tribe have a warbeast that can crush down buildings and break a gates of strongholds. Mammoth can be used break down enemy troops.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_BOMBARD_MAMMOTH</Tag>
		<English>Bombard Mammoth</English>
		<French>
			<Text>Mammouth Bombarde</Text>
			<Gender>Male</Gender>
			<Plural>0</Plural>
		</French>
		<Italian>Mammut con bombarda</Italian>
		<Polish>Mamut-Bombard</Polish>
		<Russian>Ìàìîíò ñ ïóøêîé</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_NEANDERTHAL_MAMMOTH_RIDER</Tag>
		<English>Neanderthal Mammoth Rider</English>
		<Russian>Íåàíä. ìàìîíò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_SUBDUED_MAMMOTH</Tag>
		<English>Subdued Mammoth</English>
		<French>
			<Text>Mammouth (App.)</Text>
			<Gender>Male</Gender>
			<Plural>0</Plural>
		</French>
		<German>
			<Text>Gefangenes Mammut:Gefangenen Mammuts:Gefangenen Mammut:Gefangene Mammut:Gefangene Mammuts:Gefangenen Mammuts:Gefangenen Mammuts:Gefangenen Mammuts</Text>
			<Gender>Neuter</Gender>
			<Plural>0:0:0:0:1:1:1:1</Plural>
		</German>
		<Italian>
			<Text>Mammut addomesticato</Text>
			<Gender>Male</Gender>
			<Plural>0</Plural>
		</Italian>
		<Polish>Poskromiony Mamut</Polish>
		<Russian>Ìàìîíò (ðó÷í.)</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TRAINED_MAMMOTH</Tag>
		<English>Mammoth Rider</English>
		<French>
			<Text>Chevaucheur de Mammouth</Text>
			<Gender>Male</Gender>
			<Plural>0</Plural>
		</French>
		<German>Mammothreiter</German>
		<Italian>Cavalcatore di mammut</Italian>
		<Spanish>
			<Text>Jinete de mamut</Text>
			<Gender>Male</Gender>
			<Plural>0</Plural>
		</Spanish>
		<Polish>Jeździec (Mamut)</Polish>
		<Russian>Íàåçäíèê íà ìàìîíòå</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TRAINED_MAMMOTH_PEDIA</Tag>
		<English>You raised your own mammoth pup, broke it to the saddle and trained it for war. You might ride your massive mount on raids but your primary duty is to hunt down marauding raiders in your own clan's lands. Few will stand and face a 10' war-mammoth. Fewer will face that mammoth with a warrior on its back.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_WAR_MAMMOTH</Tag>
		<English>War Mammoth</English>
		<French>
			<Text>Mammouth de Guerre</Text>
			<Gender>Male</Gender>
			<Plural>0</Plural>
		</French>
		<Italian>Mammut da guerra</Italian>
		<Spanish>
			<Text>Mamut de guerra</Text>
			<Gender>Male</Gender>
			<Plural>0</Plural>
		</Spanish>
		<Polish>Mamut Bojowy</Polish>
		<Russian>Áîåâîé ìàìîíò</Russian>
	</TEXT>
</Civ4GameText>

=== caveman2cosmos/Caveman2Cosmos/Assets/XML/Text/Alt_Timelines/Megafauna_Units/Big_Cats/Big_Cats_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_BUILDING_ANIMAL_TOTEM_CATS</Tag>
		<English>Military Standard (Big Cats)</English>
		<French>Standards Militaires (Félins)</French>
		<Italian>
			<Text>Mascotte dell'esercito (Felini)</Text>
			<Gender>Female</Gender>
			<Plural>0</Plural>
		</Italian>
		<Polish>Sztandar Wojskowy (Wielkie Koty)</Polish>
		<Russian>Òîòåì «Êîøêà»</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_ANIMAL_TOTEM_CATS_HELP</Tag>
		<English>[ICON_BULLET]Build Feline buildings and units faster in this city.</English>
		<French>Construit les bâtiments et unités félines plus vite dans cette Ville.</French>
		<Italian>Questo edificio ti permette di addestrare le unità feline più velocemente.</Italian>
		<Polish>Buduj budynki i jednostki Wielkich Kotów szybciej w Twoim mieście.</Polish>
		<Russian>[ICON_BULLET][COLOR_YELLOW]Подсказка: [COLOR_REVERT]стройте кошачьи питомники в городе, чтобы дрессировать ручных и сторожевых кошек.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BIG_CAT_TRAINER</Tag>
		<English>Animal Trainer (Big Cat)</English>
		<French>Entraineur de Félins</French>
		<Polish>Treser Wielkich Kotów</Polish>
		<Russian>Ïðèðó÷åíèå êîøåê</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BIG_CAT_TRAINER_EFFECT</Tag>
		<English>Effect - Heritage - Big Cats</English>
		<French>Effet (Entraineur de Félins)</French>
		<Polish>Efekt - Treser Wielkich Kotów</Polish>
		<Russian>Ïèòîìíèê êîøåê</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BIG_CAT_TRAINER_PEDIA</Tag>
		<English>Cat training is the process of modifying a wild cat's behavior for entertainment or companionship purposes. Training is commonly used to reduce unwanted or problematic behaviors in wild cats, to enhance interactions between humans and cats, and to allow them to coexist comfortably. There are various methods for training cats which employ different balances between reward and punishment.</English>
		<Russian>Дрессировка кошки - это процесс изменения поведения дикой кошки в развлекательных или дружеских целях. Дрессировка обычно используется для уменьшения нежелательного или проблемного поведения у диких кошек, для улучшения взаимодействия между людьми и кошками и для того, чтобы позволить им комфортно сосуществовать. Существуют различные методы дрессировки кошек, в которых используется различный баланс между вознаграждением и наказанием.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BIG_CAT_TRAINER_STRATEGY</Tag>
		<English>[COLOR_BUILDING_TEXT]Big Cat Trainer[COLOR_REVERT] is required to train cat units.</English>
		<French>[COLOR_BUILDING_TEXT]Entraineur de Félins[COLOR_REVERT] est requis pour entraîner des unités félines.</French>
		<Russian>[COLOR_BUILDING_TEXT]Приручение кошек[COLOR_REVERT] требуется для обучения кошачьих отрядов.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_POLICE_CAT</Tag>
		<English>Police Cat Trainer</English>
		<French>Entraineur de Félins Limiers</French>
		<Polish>Treser Kotów Policyjnych</Polish>
		<Russian>Ïîëèãîí äëÿ êîøåê</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_POLICE_CAT_PEDIA</Tag>
		<English>TBD</English>
		<Russian>TBD</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_POLICE_CAT_STRATEGY</Tag>
		<English>TBD</English>
		<Russian>TBD</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_FELINE_SUPERIOR</Tag>
		<English>Felis Superior</English>
		<French>Félin Cybernétique</French>
		<Russian>Ñóïåðêîøêà</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_FELINE_SUPERIOR_STRATEGY</Tag>
		<English>[COLOR_UNIT_TEXT]Felis Superior[COLOR_REVERT] its similar unit as [COLOR_UNIT_TEXT]Cyber Dog[COLOR_REVERT], but instead dogs its using bioenhanced panthers. Its ideal to police action and to thwart enemy spies and criminal units.</English>
		<Russian>[COLOR_UNIT_TEXT]Суперкошка[COLOR_REVERT] - отряд, аналогичный [COLOR_UNIT_TEXT]Суперпсу[COLOR_REVERT], где вместо собак ее используют биологически модифицированных пантер. Идеально подходит для действий полиции и для противодействия вражеским шпионам и преступникам.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_GUARDCAT</Tag>
		<English>Guard Cat</English>
		<French>Félin de surveillance</French>
		<Polish>Kot Stróżujący</Polish>
		<Russian>Ñòîðîæåâàÿ êîøêà</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_GUARDCAT_STRATEGY</Tag>
		<English>[COLOR_UNIT_TEXT]Guard Cat[COLOR_REVERT] its similar unit as [COLOR_UNIT_TEXT]Guard Dog[COLOR_REVERT], but instead dogs its using trained panthers. Its ideal to thwart enemy spies and criminal units and as skirmisher.</English>
		<Russian>[COLOR_UNIT_TEXT]Сторожевая кошка[COLOR_REVERT] - аналог [COLOR_UNIT_TEXT]Сторожевого пса[COLOR_REVERT], но здесь вместо собак используются дрессированные пантеры. Идеально подходит для борьбы с вражескими шпионами и разбойниками, а также в качестве застрельщика в начале сражения.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_POLICE_CAT</Tag>
		<English>Police Cat</English>
		<French>Félin Limier</French>
		<Polish>Kot Policyjny</Polish>
		<Russian>Ïîëèö. êîøêà</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_POLICE_CAT_STRATEGY</Tag>
		<English>[COLOR_UNIT_TEXT]Police Cat[COLOR_REVERT] its similar unit as [COLOR_UNIT_TEXT]Police Dog[COLOR_REVERT], but instead dogs its using trained panthers. Its ideal to police action and to thwart enemy spies and criminal units.</English>
		<Russian>[COLOR_UNIT_TEXT]Полицейская кошка[COLOR_REVERT] - отряд, аналогичный [COLOR_UNIT_TEXT]Полицейскому псу[COLOR_REVERT], где вместо собак ее используют специально обученных пантер. Идеально подходит для действий полиции и для противодействия вражеским шпионам и преступным группировкам.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TRAINEDCAT</Tag>
		<English>Trained Cat</English>
		<French>Félin dressé</French>
		<Polish>Tresowany Kot</Polish>
		<Russian>Äîìàøíÿÿ êîøêà</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TRAINEDCAT_STRATEGY</Tag>
		<English>[COLOR_UNIT_TEXT]Trained Cat[COLOR_REVERT] its similar unit as [COLOR_UNIT_TEXT]Trained Dog[COLOR_REVERT], but instead dogs its using trained panthers. Its ideal against criminal units and as skirmisher.</English>
		<Russian>[COLOR_UNIT_TEXT]Домашняя кошка[COLOR_REVERT] - аналог [COLOR_UNIT_TEXT]Домашней собаки[COLOR_REVERT], но здесь вместо собак используются дрессированные пантеры. Идеально подходит для борьбы с вражескими шпионами и разбойниками, а также в качестве застрельщика в начале сражения.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_WARCAT</Tag>
		<English>War Cat</English>
		<French>Félin de combat</French>
		<Polish>Kot Bojowy</Polish>
		<Russian>Áîåâàÿ êîøêà</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_WARCAT_PEDIA</Tag>
		<English>Cat training is the process of modifying a wild cat's behavior for entertainment or companionship purposes. Training is commonly used to reduce unwanted or problematic behaviors in wild cats, to enhance interactions between humans and cats, and to allow them to coexist comfortably. There are various methods for training cats which employ different balances between reward and punishment.</English>
		<Russian>Дрессировка кошки - это процесс изменения поведения дикой кошки в развлекательных или дружеских целях. Дрессировка обычно используется для уменьшения нежелательного или проблемного поведения у диких кошек, для улучшения взаимодействия между людьми и кошками и для того, чтобы позволить им комфортно сосуществовать. Существуют различные методы дрессировки кошек, в которых используется различный баланс между вознаграждением и наказанием.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_WARCAT_STRATEGY</Tag>
		<English>[COLOR_UNIT_TEXT]War Cat[COLOR_REVERT] its similar unit as [COLOR_UNIT_TEXT]Wardog[COLOR_REVERT], but instead dogs its using trained panthers. Its ideal against criminal units and as skirmisher.</English>
		<Russian>[COLOR_UNIT_TEXT]Боевая кошка[COLOR_REVERT] - аналог [COLOR_UNIT_TEXT]Боевого пса[COLOR_REVERT], но здесь вместо собак используются дрессированные пантеры. Идеально подходит для борьбы с вражескими шпионами и разбойниками, а также в качестве застрельщика в начале сражения.</Russian>
	</TEXT>
</Civ4GameText>

=== caveman2cosmos/Caveman2Cosmos/Assets/Modules/My_Mods (unloaded)/Antiquities (broken)/Antiquities_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_BONUS_ANTIQUITIES_GRAVE_GOODS_CAVE</Tag>
		<English>Antiquities - Grave Goods (Cave)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BONUS_ANTIQUITIES_GRAVE_GOODS_EARTH</Tag>
		<English>Antiquities - Grave Goods (Earth)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BONUS_ANTIQUITIES_GRAVE_GOODS_FIRE</Tag>
		<English>Antiquities - Grave Goods (Fire)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BONUS_ANTIQUITIES_GRAVE_GOODS_SKY</Tag>
		<English>Antiquities - Grave Goods (Sky)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BONUS_BURIAL_GOODS_PEDIA</Tag>
		<English>Grave Goods made in ancient times and traded as antiquities to the rich and Museums.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BURIAL_GOODS_CAVE</Tag>
		<English>Grave Goods (Cave)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BURIAL_GOODS_EARTH</Tag>
		<English>Grave Goods (Earth)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BURIAL_GOODS_FIRE</Tag>
		<English>Grave Goods (Fire)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BURIAL_GOODS_PEDIA</Tag>
		<English>Game auto builds used to provide antiquities at Archaeology.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BURIAL_GOODS_SKY</Tag>
		<English>Grave Goods (Sky)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_GRAVE_GOODS</Tag>
		<English>Grave Goods</English>
	</TEXT>
</Civ4GameText>
