=== caveman2cosmos/Caveman2Cosmos/Assets/XML/Schema/Civ4GameText.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.firaxis.com" elementFormDefault="qualified" targetNamespace="http://www.firaxis.com">
  <xs:element name="Civ4GameText">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="TEXT" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:all>
              <xs:element ref="Tag"/>
              <xs:element name="English" type="Gametext"/>
              <xs:element name="French" type="Gametext" minOccurs="0"/>
              <xs:element name="German" type="Gametext" minOccurs="0"/>
              <xs:element name="Italian" type="Gametext" minOccurs="0"/>
              <xs:element name="Spanish" type="Gametext" minOccurs="0"/>
              <xs:element name="Polish" type="Gametext" minOccurs="0"/>
              <xs:element name="Russian" type="Gametext" minOccurs="0"/>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Tag">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="TXT_[\c-[:]]*|AI_DIPLO_[\c-[:]]*|USER_DIPLO_[\c-[:]]*|INTERFACE_[\c-[:]]*"/>
        <xs:whiteSpace value="collapse"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:complexType mixed="true" name="Gametext">
    <xs:all>
      <xs:element name="Text" type="xs:string" minOccurs="0"/>
      <xs:element name="Gender" type="xs:NMTOKEN" minOccurs="0"/>
      <xs:element name="Plural" type="xs:NMTOKEN" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
</xs:schema>

=== caveman2cosmos/Caveman2Cosmos/Assets/XML/GameText/Modules/Alt_Timelines/Megafauna_Units/Bison_Rider/BisonRider_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_BUILDING_ANIMAL_TOTEM_BISON</Tag>
		<English>Military Standard (Bison)</English>
		<French>Standards Militaires (Bisons)</French>
		<Polish>Sztandar Wojskowy (Bizon)</Polish>
		<Russian>Òîòåì «Áèçîí»</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_ANIMAL_TOTEM_BISON_HELP</Tag>
		<English>[ICON_BULLET]Build Bison buildings and units faster in this city.</English>
		<French>Construit les bâtiments et unités bisons plus vite dans cette Ville.</French>
		<Polish>Konstuuj budynki i werbuj jednostki bizonów szybciej w tym mieście.</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BISON_TRAINER</Tag>
		<English>Animal Trainer (Bison)</English>
		<French>
			<Text>Dresseur de Bisons</Text>
			<Gender>Male</Gender>
			<Plural>0</Plural>
		</French>
		<Italian>Allevatore di bisonti</Italian>
		<Polish>Treser Bizonów</Polish>
		<Russian>Ïðèðó÷åíèå áèçîíîâ</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BISON_TRAINER_EFFECT</Tag>
		<English>Effect - Heritage - Bison</English>
		<French>Effet - Patrimoine (Bisons)</French>
		<Polish>Efekt - Dziedzictwo - Bizon</Polish>
		<Russian>Ïèòîìíèê áèçîíîâ</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BISON_TRAINER_HERITAGE</Tag>
		<English>Heritage - Bison</English>
		<French>Patrimoine (Bisons)</French>
		<Polish>Dziedzictwo - Bizon</Polish>
		<Russian>Ðàçâåäåíèå áèçîíîâ</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BISON_TRAINER_HERITAGE_PEDIA</Tag>
		<English>Instead of only being able to train Bison units in the city you built the wonder in this building allows them to be built in any of your cities. It can only be built in the city with the Bison Trainer World Wonder.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BISON_TRAINER_PEDIA</Tag>
		<English>There is no evidence bison were ever trained for warfare. The [COLOR_BUILDING_TEXT]Bison Trainer[COLOR_REVERT] building is part of the [COLOR_HIGHLIGHT_TEXT]alternate timeline technologies[COLOR_REVERT]. Technologies that might have been.</English>
		<Italian>Non ci sono prove che i bisonti siano mai stati usati in guerra. L'[COLOR_BUILDING_TEXT]Allevatore di bisonti[COLOR_REVERT] fa parte delle [COLOR_HIGHLIGHT_TEXT]alternate timeline technologies[COLOR_REVERT]. Tecnologie che potrebbero essere esistite. [COLOR_HIGHLIGHT_TEXT]alternate timeline technologies[COLOR_REVERT]. Technologies that might have been.</Italian>
		<Polish>Nie ma dowodów na istnienie tej jednostki, jest ona częścią tzw. [COLOR_HIGHLIGHT_TEXT]technologii alternatywnej ścieżki historycznej[COLOR_REVERT].</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_BISON_RIDER</Tag>
		<English>Bison Rider</English>
		<French>
			<Text>Chevaucheur de Bison</Text>
			<Gender>Male</Gender>
			<Plural>0</Plural>
		</French>
		<Italian>Cavalcatore di bisonti</Italian>
		<Polish>Jeździec (Bizon)</Polish>
		<Russian>Íàåçäíèê íà áèçîíå</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_BISON_RIDER_PEDIA</Tag>
		<English>There is no evidence this unit was ever used. It is part of the [COLOR_HIGHLIGHT_TEXT]alternate timeline technologies[COLOR_REVERT]. Technologies that might have been.</English>
		<Italian>Non c'è alcuna prova che quest'unità sia mai stata usata in battaglia. Fa parte delle [COLOR_HIGHLIGHT_TEXT]alternate timeline technologies[COLOR_REVERT]. Tecnologie che potrebbero essere esistite.</Italian>
		<Polish>Nie ma dowodów na istnienie tej jednostki, jest ona częścią tzw. [COLOR_HIGHLIGHT_TEXT]technologii alternatywnej ścieżki historycznej[COLOR_REVERT].</Polish>
	</TEXT>
</Civ4GameText>

=== caveman2cosmos/Caveman2Cosmos/Assets/XML/Text/Custom_Religions/Caodai/CaoDai_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CAODAI_CATHEDRAL</Tag>
		<English>Cao Dai Cathedral</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CAODAI_CATHEDRAL_PEDIA</Tag>
		<English>In Civilization IV, a cathedral is defined as an especially large and ornate religious building where the faithful worship. Only the most prosperous cities can afford to create cathedrals, as they require huge amounts of raw material and years of dedicated labor by skilled craftsmen. For example, the Notre Dame Cathedral in Paris, France, took over two centuries to complete.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CAODAI_CATHEDRAL_STRATEGY</Tag>
		<English>The [COLOR_BUILDING_TEXT]Mosque[COLOR_REVERT] ([COLOR_BUILDING_TEXT]CaoDai Cathedral[COLOR_REVERT]) greatly increases a city's cultural output. It makes a city's citizens happy (if [COLOR_HIGHLIGHT_TEXT]CaoDai[COLOR_REVERT] is the state religion).</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CAODAI_MONASTERY</Tag>
		<English>Cao Dai Monastery</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CAODAI_MONASTERY_PEDIA</Tag>
		<English>A monastery is a building where monks can retreat from the world and concentrate upon the divine. Usually a monastery will have strict rules of conduct to protect its unworldly members from temptation. In some monasteries, the monks are totally silent; in others no visitors are allowed inside. Monasteries usually have many daily rituals and religious services.[PARAGRAPH:1]Throughout the ages monasteries have often been centers of learning. In remote areas the monks may be the only literate people for miles around. Monks have often been employed as scribes, copying out the words of their religion's sacred scripture. Monasteries frequently have extensive libraries, holding religious, scientific, medical and philosophical texts.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CAODAI_MONASTERY_STRATEGY</Tag>
		<English>[COLOR_BUILDING_TEXT]Monasteries[COLOR_REVERT] allow you to create [COLOR_UNIT_TEXT]Missionaries[COLOR_REVERT], who can spread the faith in other cities. They also provide culture and a slight boost to research.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CAODAI_SHRINE</Tag>
		<English>Great Temple Tay Ninh</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CAODAI_SHRINE_PEDIA</Tag>
		<English>The Great Temple is 140 m long and 40 m wide. It has 4 towers each with a different name: Tam Dai, Hiep Thien Dai, Cuu Trung Dai, and Bat Quai Dai. The interior of the temple consists of a colonnaded hall and a sanctuary. The 2 rows of columns are decorated with dragons and are coated in white, red, and blue paint. The domed ceiling is divided into 9 parts similar to a night sky full of stars and symbolizing heaven. Under the dome is a giant star-speckled blue globe on which is painted the Divine Eye, the official symbol of Caodaism. Cao Dai followers worship Jesus Christ, Confucius, Taoism, and Buddha.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CAODAI_SHRINE_STRATEGY</Tag>
		<English>The [COLOR_BUILDING_TEXT]Great Temple Tay Ninh[COLOR_REVERT] ([COLOR_BUILDING_TEXT]CaoDai Shrine[COLOR_REVERT]) produces one gold each turn for every city in the world that practises [COLOR_HIGHLIGHT_TEXT]CaoDai[COLOR_REVERT]. It also spreads [COLOR_HIGHLIGHT_TEXT]CaoDai[COLOR_REVERT] thoughout the world and increases its city's chances of generating a [COLOR_UNIT_TEXT]Great Prophet[COLOR_REVERT].</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CAODAI_TEMPLE</Tag>
		<English>Cao Dai Temple</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CAODAI_TEMPLE_PEDIA</Tag>
		<English>In Civilization IV, a temple is defined as a building where the faithful come to worship. Christians call their temples "churches," while Muslims call theirs "mosques," and Jews call theirs, simply, "temples." Temples are far more common than cathedrals, but much less large and ornate. Even the smallest village can possess a temple.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CAODAI_TEMPLE_STRATEGY</Tag>
		<English>[COLOR_BUILDING_TEXT]Temples[COLOR_REVERT] increase a city's happiness and culture. They are especially useful for expanding your civilization's borders during the early game.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_TECH_CAO_DAI</Tag>
		<English>Cao Dai</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_TECH_CAO_DAI_PEDIA</Tag>
		<English>[PARAGRAPH:0]Cao Dai (or "High Tower", a Taoist epithet for the supreme god) is a syncretist Vietnamese religious movement with a strongly nationalist political character. Cao Dai draws upon ethical precepts from Confucianism, occult practices from Taoism, theories of karma and rebirth from Buddhism, and a hierarchical organization (including a pope) from Roman Catholicism. Its pantheon of saints includes such diverse figures as the Buddha, Confucius, Jesus Christ, Muhammad, Pericles, Julius Caesar, Joan of Arc, Victor Hugo, and Sun Yat-sen. In Cao Dai, God is represented as an eye in a triangle, a symbol that appears on the facades of the sect’s temples. The religion’s organization is patterned after that of Roman Catholicism, with a pope, cardinals, and archbishops. Worship involves elaborate rituals and festivals.[PARAGRAPH:2]In 1919 Ngo Van Chieu (q.v.), an administrator for the French in Indochina, received a communication from the supreme deity during a table-moving séance. Chieu became the prophet of the new religion, which was formally established in 1926. A Cao Dai army was established in 1943 during the Japanese occupation of Indochina. After the war the Cao Dai was an effective force in national politics; it first supported, then opposed, Premier Ngo Dinh Diem. In 1955–56 Diem disbanded the Cao Dai army and forced the sect’s pope, Pham Cong Tac, into exile. After the communist takeover in 1975, Cao Dai was reportedly repressed by the government. Centres of worship were established in Vietnamese refugee communities abroad, however, and by the early 1990s Cao Dai was reported to have some two million adherents in Vietnam, Cambodia, France, and the United States. Headquarters of the religion are at Tay Ninh (q.v.), near Ho Chi Minh City (formerly Saigon).[PARAGRAPH:2]- Encyclopaedia Britannica</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_TECH_CAO_DAI_QUOTE</Tag>
		<English>The ultimate goal of CaoDaists is to be reunified with the All That Is, to return home.[PARAGRAPH:2]- Hum Dac Bui,[PARAGRAPH:1][SPACE][SPACE]"Cao Dai: Faith of Unity"</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_TECH_CAO_DAI_STRATEGY</Tag>
		<English>Research Cao Dai to found a religion.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_CAODAI_MISSIONARY</Tag>
		<English>Cao Dai Missionary</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_CAODAI_MISSIONARY_STRATEGY</Tag>
		<English>Use this missionary to actively spread [COLOR_HIGHLIGHT_TEXT]CaoDai[COLOR_REVERT] in friendly cities (or rival cities with whom you have [COLOR_HIGHLIGHT_TEXT]Open Borders[COLOR_REVERT]). This increases your income if you have the [COLOR_BUILDING_TEXT]Masjid al-Haram[COLOR_REVERT].</English>
	</TEXT>
</Civ4GameText>

=== caveman2cosmos/Caveman2Cosmos/Assets/XML/GameText/Modules/Pepper2000/Emancipation_Building_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_BUILDING_EMANCIPATION_PROCLAMATION</Tag>
		<English>Emancipation Proclamation</English>
		<French>Proclamation d'Emancipation</French>
		<Russian>Прокламация об освобождении</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_EMANCIPATION_PROCLAMATION_EFFECT</Tag>
		<English>Effect - Emancipation Proclamation</English>
		<French>Effet - Proclamation d'Emancipation</French>
		<Italian>Effetto - Proclamazione di emancipazione</Italian>
		<Russian>Прокламация об освобождении - Эффект</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_EMANCIPATION_PROCLAMATION_EFFECT_PEDIA</Tag>
		<English>The Emancipation Proclamation was a presidential proclamation and executive order issued by President Abraham Lincoln on January 1, 1863. In a single stroke, it changed the federal legal status of more than 3 million enslaved persons in the designated areas of the South from 'slave' to 'free'. It had the practical effect that as soon as a slave escaped the control of the Confederate government, by running away or through advances of federal troops, the slave became legally free. Eventually it reached and liberated all of the designated slaves. It was issued as a war measure during the American Civil War, directed to all of the areas in rebellion and all segments of the executive branch (including the Army and Navy) of the United States.</English>
		<French>La Proclamation d'Emancipation était une proclamation présidentielle et un décret exécutif émis par le président Abraham Lincoln le 1er janvier 1863. D'un seul coup, elle a changé le statut juridique fédéral de plus de 3 millions de personnes asservies dans les zones désignées du Sud, du statut d'esclave à être libre. Cela eut pour effet pratique que dès qu'un esclave échappait au contrôle du gouvernement confédéré, en s'enfuyant ou en avançant des troupes fédérales, l'esclave devenait légalement libre. Finalement, il a atteint et libéré tous les esclaves désignés. Cette proclamation est en partie à l'origine de la guerre de Sécession, dirigé contre toutes les régions en rébellion et tous les segments de l'exécutif (y compris l'armée et la marine) des États-Unis.</French>
		<Russian>«Прокламация об освобождении рабов» — документ, состоящий из двух указов Авраама Линкольна, изданных во время гражданской войны в США. Первый указ, изданный 22 сентября 1862 года, объявлял свободными всех рабов в любом штате США, не возвратившемся в состав США до 1 января 1863 года. Второй указ, изданный 1 января 1863 года, назвал 10 отдельных штатов, на которые будет распространяться отмена рабства. Тринадцатая поправка к Конституции США, освободившая рабов во всех штатах, была принята незадолго до окончания Гражданской войны 31 января 1865 года.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_EMANCIPATION_PROCLAMATION_HELP</Tag>
		<English>[ICON_BULLET]Build this building to disable Human Sacrifice, Cannibalism and Slavery worldviews. Slavery used to disable factory, now it just has big maluses, that accumulate over time from techs</English>
		<French>[ICON_BULLET]Construisez ce bâtiment pour désactiver les visions du monde sur le sacrifice humain, le cannibalisme et l'esclavage. L'esclavage désactivait l'usine, maintenant il engendre juste de gros malus, qui s'accumulent avec le temps et les découvertes des technologies.</French>
		<Russian>[ICON_BULLET][COLOR_YELLOW]Подсказка:[COLOR_REVERT]Постройте это здание, чтобы отключить мировоззрения человеческих жертвоприношений, людоедства и рабства. Прокламация раньше отключала невольничьи рынки, теперь же она убирает и штрафы, которые со временем накапливаются от технологий</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_EMANCIPATION_PROCLAMATION_PEDIA</Tag>
		<English>The Emancipation Proclamation was a presidential proclamation and executive order issued by President Abraham Lincoln on January 1, 1863. In a single stroke, it changed the federal legal status of more than 3 million enslaved persons in the designated areas of the South from 'slave' to 'free'. It had the practical effect that as soon as a slave escaped the control of the Confederate government, by running away or through advances of federal troops, the slave became legally free. Eventually it reached and liberated all of the designated slaves. It was issued as a war measure during the American Civil War, directed to all of the areas in rebellion and all segments of the executive branch (including the Army and Navy) of the United States.</English>
		<French>La Proclamation d'Emancipation était une proclamation présidentielle et un décret exécutif émis par le président Abraham Lincoln le 1er janvier 1863. D'un seul coup, elle a changé le statut juridique fédéral de plus de 3 millions de personnes asservies dans les zones désignées du Sud, du statut d'esclave à être libre. Cela eut pour effet pratique que dès qu'un esclave échappait au contrôle du gouvernement confédéré, en s'enfuyant ou en avançant des troupes fédérales, l'esclave devenait légalement libre. Finalement, il a atteint et libéré tous les esclaves désignés. Cette proclamation est en partie à l'origine de la guerre de Sécession, dirigé contre toutes les régions en rébellion et tous les segments de l'exécutif (y compris l'armée et la marine) des États-Unis.</French>
		<Russian>«Прокламация об освобождении рабов» — документ, состоящий из двух указов Авраама Линкольна, изданных во время гражданской войны в США. Первый указ, изданный 22 сентября 1862 года, объявлял свободными всех рабов в любом штате США, не возвратившемся в состав США до 1 января 1863 года. Второй указ, изданный 1 января 1863 года, назвал 10 отдельных штатов, на которые будет распространяться отмена рабства. Тринадцатая поправка к Конституции США, освободившая рабов во всех штатах, была принята незадолго до окончания Гражданской войны 31 января 1865 года.</Russian>
	</TEXT>
</Civ4GameText>

=== caveman2cosmos/Caveman2Cosmos/Assets/XML/Text/Beastmaster_Help_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_AARDVARK_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Worker's Totem, Zoo and Taxidermist</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Standards Militaires (Ouvriers), Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Òîòåì Ðàáîòíèêà, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_BEAR_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Bear Cage and Dancing Bear</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Cage à Ours, et Ours danseur</French>
		<Italian>[COLOR_HIGHLIGHT_TEXT]Costruisci[COLOR_REVERT] Gabbia dell'orso e Orso ballerino</Italian>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Âîëüåð ìåäâåäåé è Ïëÿøóùèé ìåäâåäü</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_BISON_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Bison Herd, Carnival, Herbivore Enclosure, Zoo and Taxidermist</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Troupeau de Bison, Carnaval, Enclos pour Herbivores, Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Ñòàäî áèçîíîâ, Êàðíàâàë, Âîëüåð òðàâîÿäíûõ, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_BOAR_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Pig Herd, Herbivore Enclosure, Zoo and Taxidermist</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Troupeau de Cochons, Enclos pour Herbivores, Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Ñòàäî ñâèíåé, Êàðíàâàë, Âîëüåð òðàâîÿäíûõ, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_BUFFALO_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Buffalo Herd, Carnival, Herbivore Enclosure, Zoo and Taxidermist</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Troupeau de Buffles, Carnaval, Enclos pour Herbivores, Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Ñòàäî áóéâîëîâ, Êàðíàâàë, Âîëüåð òðàâîÿäíûõ, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_CAMEL_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Camel Herd, Carnival, Herbivore Enclosure, Zoo and Taxidermist</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Troupeau de Chameau, Carnaval, Enclos pour Herbivores, Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Ñòàäî âåðáëþäîâ, Êàðíàâàë, Âîëüåð òðàâîÿäíûõ, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_CATTLE_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Cow Herd, Carnival, Herbivore Enclosure, Zoo and Taxidermist</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Troupeau de Vaches, Carnaval, Enclos pour Herbivores, Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Ñòàäî êîðîâ, Êàðíàâàë, Âîëüåð òðàâîÿäíûõ, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_DONKEY_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Donkey Herd, Carnival, Herbivore Enclosure, Zoo and Taxidermist, May place [COLOR_HIGHLIGHT_TEXT]Donkey[COLOR_REVERT] resource on map</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Troupeau d'ânes, Carnaval, Enclos pour Herbivores, Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Ñòàäî îñëîâ, Êàðíàâàë, Âîëüåð òðàâîÿäíûõ, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_ELEPHANT_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Elephant Herd, Carnival, Herbivore Enclosure, Zoo and Taxidermist</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Troupeau d'Elephants, Carnaval, Enclos pour Herbivores, Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Ñòàäî ñëîíîâ, Êàðíàâàë, Âîëüåð òðàâîÿäíûõ, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_HIPPO_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Herbivore Enclosure, Zoo and Taxidermist</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Enclos pour Herbivores, Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Âîëüåð òðàâîÿäíûõ, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_HORSE_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Horse Herd, Carnival, Herbivore Enclosure, Zoo and Taxidermist, May place [COLOR_HIGHLIGHT_TEXT]Horse[COLOR_REVERT] resource on map</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Troupeau de chevaux, Carnaval, Enclos pour Herbivores, Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Òàáóí ëîøàäåé, Êàðíàâàë, Âîëüåð òðàâîÿäíûõ, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_LION_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Big Cat Cage</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Cage de Félins</French>
		<Italian>[COLOR_HIGHLIGHT_TEXT]Costruisci[COLOR_REVERT] Gabbia-Felini</Italian>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Âîëüåð äëÿ êîøåê</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_LLAMA_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Llama Herd, Carnival, Herbivore Enclosure, Zoo and Taxidermist</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Troupeau de Lamas, Carnaval, Enclos pour Herbivores, Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Ñòàäî ëàì, Êàðíàâàë, Âîëüåð òðàâîÿäíûõ, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_MAMMOTH_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Mammoth Herd, Carnival, Herbivore Enclosure, Zoo and Taxidermist</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Troupeau de Mammouths, Carnaval, Enclos pour Herbivores, Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Ñòàäî ìàìîíòîâ, Êàðíàâàë, Âîëüåð òðàâîÿäíûõ, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_MUSKOX_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Musk Ox Herd, Herbivore Enclosure, Zoo and Taxidermist</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Troupeau de Boeufs musqués, Enclos pour Herbivores, Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Ñòàäî îâöåáûêîâ, Êàðíàâàë, Âîëüåð òðàâîÿäíûõ, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_RHINO_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Herbivore Enclosure, Zoo and Taxidermist</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Enclos pour Herbivores, Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Âîëüåð òðàâîÿäíûõ, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_TAPIR_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Herbivore Enclosure, Zoo and Taxidermist</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Enclos pour Herbivores, Zoo et Taxidermiste</French>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Âîëüåð òðàâîÿäíûõ, Çîîïàðê è Òàêñèäåðìèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_TAMED_WOLF_HELP</Tag>
		<English>[ICON_BULLET][COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Wolf Cage, Kennels, Dog Breeder, War and Guard Dog Trainers</English>
		<French>[ICON_BULLET]Permet de [COLOR_HIGHLIGHT_TEXT]Construire[COLOR_REVERT] Cage à Loups, Chenils, Éleveur de chiens, Dresseur de Chiens de guerre et de garde</French>
		<Italian>[COLOR_HIGHLIGHT_TEXT]Costruisci[COLOR_REVERT] Gabbia-Lupi, Canile, Addomesticatore di cani, Allenatore di cani da guerra, Allenatore di cani da caccia</Italian>
		<Russian>[COLOR_HIGHLIGHT_TEXT]Ñòðîèòü[COLOR_REVERT] Âîëüåð äëÿ âîëêîâ, Ñîáà÷üè áóäêè, Äðåññ. Áîåâûõ è Ñòîðîæ. ïñîâ</Russian>
	</TEXT>
</Civ4GameText>
