=== caveman2cosmos/Caveman2Cosmos/Assets/XML/Schema/Civ4GameText.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.firaxis.com" elementFormDefault="qualified" targetNamespace="http://www.firaxis.com">
  <xs:element name="Civ4GameText">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="TEXT" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:all>
              <xs:element ref="Tag"/>
              <xs:element name="English" type="Gametext"/>
              <xs:element name="French" type="Gametext" minOccurs="0"/>
              <xs:element name="German" type="Gametext" minOccurs="0"/>
              <xs:element name="Italian" type="Gametext" minOccurs="0"/>
              <xs:element name="Spanish" type="Gametext" minOccurs="0"/>
              <xs:element name="Polish" type="Gametext" minOccurs="0"/>
              <xs:element name="Russian" type="Gametext" minOccurs="0"/>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Tag">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="TXT_[\c-[:]]*|AI_DIPLO_[\c-[:]]*|USER_DIPLO_[\c-[:]]*|INTERFACE_[\c-[:]]*"/>
        <xs:whiteSpace value="collapse"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:complexType mixed="true" name="Gametext">
    <xs:all>
      <xs:element name="Text" type="xs:string" minOccurs="0"/>
      <xs:element name="Gender" type="xs:NMTOKEN" minOccurs="0"/>
      <xs:element name="Plural" type="xs:NMTOKEN" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
</xs:schema>

=== caveman2cosmos/Caveman2Cosmos/Assets/XML/GameText/Entertainer_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_MISSION_ENTERTAIN_CITY</Tag>
		<English>Entertain the city.</English>
		<French>Divertir la ville.</French>
		<Italian>Intrattieni la città.</Italian>
		<Polish>Rozbaw miasto.</Polish>
		<Russian>Ðàçâëåêè ãîðîä.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MISSION_ENTERTAIN_CITY_HELP</Tag>
		<English>Spread your culture to the city and reduce anarchy length.</English>
		<French>Répand votre culture dans la ville, et réduit la durée de l'anarchie.</French>
		<Italian>Diffondi la tua cultura nella città per ridurre la durata del periodo di anarchia.</Italian>
		<Polish>Rozszerz swoją kultur w mieście i zmniejsz czas trwania anarchii.</Polish>
		<Russian>Ðàñïðîñòðàíÿÿ âàøó êóëüòóðó â ãîðîäå, âû ýòèì ñàìûì ñîêðàùàåòå ïðîäîëæèòåëüíîñòü àíàðõèè.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_OUTCOME_ENTERTAIN_CITY</Tag>
		<English>Entertain the city.</English>
		<French>Divertir la ville.</French>
		<Italian>Hai intrattenuto la città.</Italian>
		<Polish>Rozbaw miasto.</Polish>
		<Russian>Ïîâåñåëè òîëïó.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_OUTCOME_ENTERTAIN_CITY_MESSAGE</Tag>
		<English>Entertain the city.</English>
		<French>Divertir la ville.</French>
		<Italian>Hai intrattenuto la città.</Italian>
		<Polish>Rozbaw miasto.</Polish>
		<Russian>Óñòðîèòü ñïåêòàêëü.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_PROMOTION_EXPERIENCED_ARTIST</Tag>
		<English>Experienced Artist</English>
		<French>Artiste expérimenté</French>
		<Italian>Artista esperto</Italian>
		<Polish>Doświadczony Artysta</Polish>
		<Russian>Çàñëóæåííûé àðòèñò</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_BARD</Tag>
		<English>Bard</English>
		<French>Barde</French>
		<Italian>Bardo</Italian>
		<Russian>Áàðä</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_BARD_PEDIA</Tag>
		<English>Celtic bards, poets and singers met from the 11th to the 17th century at the courts of Ireland, Scotland, Wales and Brittany. Nowadays, the "bard" is defined as an outstanding artist who performs his own literary and musically refined works, with the accompaniment of an instrument, usually a guitar.</English>
		<Polish>Bard celtycki poeta i pieśniarz, spotykany od XI do XVII wieku na dworach Irlandii, Szkocji, Walii i Bretanii. Współcześnie mianem "bard" określa si wybitnego artyst, wykonującego własne, literacko i muzycznie dopracowane utwory z towarzyszeniem instrumentu zwykle gitary.</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_CELEBRITY</Tag>
		<English>Celebrity</English>
		<French>Célébrité</French>
		<Italian>Celebrità</Italian>
		<Polish>Celebryta</Polish>
		<Russian>Çíàìåíèòîñòü</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_CELEBRITY_PEDIA</Tag>
		<English>In which corner of the world is not known a Jordan's slum or a Beckham's free kick? Since mass media delivers any kind of thing to any place in the world, everybody good enough in something is able to influence the world's culture... even Paris Hilton has a piece of this.</English>
		<Italian>In quale angolo del mondo la gente non conosce una schiacciata di Michael Jordan o un calcio di punizione di Beckham? Da quando i mass media erogano qualsiasi tipo di cosa in qualsiasi luogo del mondo, tutti coloro che sono abbastanza bravi in qualcosa sono in grado di influenzare la cultura mondiale... anche Paris Hilton.</Italian>
		<Polish>Celebryta (dawniej spotykana również forma celebryt obecnie nienotowana przez słowniki), rodz. żeński celebrytka, l.mn. celebryci (ang. celebrity, z łac. celebrare) termin odnoszący si do osoby czsto wystpującej w środkach masowego przekazu i wzbudzającej ich zainteresowanie, bez wzgldu na pełniony przez nią zawód (choć najczściej są to aktorzy, piosenkarze, uczestnicy reality show, sportowcy czy dziennikarze). Zgodnie z definicją sformułowaną przez Daniela Boorstina w 1961 roku celebryt to osoba, która jest znana z tego, że jest znana. Słowo celebryt nie jest dokładnym synonimem gwiazdy, sławy, idola, autorytetu. Ze wzgldu na możliwość szerokiego oddziaływania społecznego celebryci wykorzystywani są w działaniach reklamowych.</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_STORY_TELLER</Tag>
		<English>Story Teller</English>
		<French>Conteur d'histoire</French>
		<Italian>Cantastorie</Italian>
		<Polish>Gawdziarz</Polish>
		<Russian>Ñêàçèòåëü</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_STORY_TELLER_PEDIA</Tag>
		<English>Since the beginning of time, story telling has been an art capable of influence in a country culture for ever, and able to make the story teller an important person in society.</English>
		<Italian>Sin dall'alba dei tempi, l'arte dei cantastorie è stata in grado di influenzare la cultura di una nazione per sempre, in grado di rendere il cantastorie una persona importante per la società.</Italian>
		<Polish>Klechdarz (bajdała) osoba zajmująca si opowiadaniem lub wymyślaniem bajek, przypowieści lub klechd. Czsto opowiada o legendarnej przeszłości regionu, niezwykłych wydarzeniach i postaciach czy osobliwościach krajobrazu. W Polsce klechdarze stanowią dość liczną grup wśród mieszkańców Podhala i Tatr.</Polish>
		<Russian>С незапамятных времен рассказывание историй было искусством, способным навсегда влиять на культуру страны и сделать сказителя важной личностью в обществе.</Russian>
	</TEXT>
</Civ4GameText>

=== caveman2cosmos/Caveman2Cosmos/Assets/Modules/Custom_Leaderheads/Sa/Sa_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>AI_DIPLO_FIRST_CONTACT_LEADER_SA_1</Tag>
		<English>I am [OUR_NAME] of the [OUR_EMPIRE]. Shall we discuss our future together? If one does not look ahead, one remains behind.</English>
		<French>Je suis [OUR_NAME] de l'[OUR_EMPIRE]. Allons-nous discuter de notre avenir ensemble? Si on ne regarde pas l'avenir, on reste derrière.</French>
		<Polish>Jestem [OUR_NAME] z [OUR_EMPIRE]. Czy przedyskutujemy naszą, wspólną przyszłość? Jeśli jeden z nas nie będzie spoglądał w przyszłość, drugi pozostanie w tyle.</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_LEADER_SA</Tag>
		<English>Mem de Sá</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_LEADER_SA_PEDIA</Tag>
		<English>Mem de Sá (c. 1500 - March 2, 1572) was a Governor-General of Brazil from 1557-1572.He was born in Coimbra, Portugal, around 1500, the year of discovery of Brazil by a naval fleet commanded by Pedro Álvares Cabral.He was nominated the third Governor-General of Brazil in 1556, succeeding Duarte da Costa, who was Governor-General from 1553 to 1557. The seat of the government was Salvador, in the present-day state of Bahia.He was fortunate in securing the support of two important Jesuit priests, Fathers Manuel da Nóbrega (1517-1570) and José de Anchieta (1533-1597), who founded São Vicente in 1532, and São Paulo, on January 25, 1554, which is today one of the largest metropolises in the world. The Jesuits were stern and persistent missionaries of the Catholic faith with the aboriginal people, and their pacification of these warrior societies was one of the most important conquests of Mem de Sá's government. The Jesuits had conflicts with Duarte da Costa, because he supported the plantation owners, who tried to force slavery upon the Indians.Mem de Sá had also an important military and political mission when, in 1560, leading a naval expedition of 26 ships and 2,000 soldiers and sailors, he was sent by the Portuguese crown to attack France Antarctique, a colony founded by Nicolas Durand de Villegaignon, a Huguenot French vice-admiral in present day Rio de Janeiro. Fort Coligny, built by the French colonists on a small island of the Guanabara Bay was destroyed, but Mem de Sá was able to expel definitely the French invaders in 1567 only, with the help of his nephew, Estácio de Sá, who was also the founder of Rio de Janeiro on March 1, 1565. With the help of the Jesuits, Mem de Sá was able to convince the Tamoyo Confederation to withdraw their support to the Frenchmen.Mem de Sá died on March 2, 1572, in Salvador.</English>
		<Polish>Mem de Sá (ur. ok. 1500, zm. 1572) - portugalski gubernator generalny Brazylii w latach 1557 - 1572. Objęcie gubernatorstwa po Duarte da Costa, przez Mem de Sá zbiegło się z kilkoma powstaniami Indian, z chaosem panującym w Brazylii spowodowanym kłótniami jezuitów z bandeirantami, i władz kościelnych z kolonialnymi oraz z powstającymi osiedli francuskich, angielskich i flamandzkich które zbroiły Indian. Mem de Sá pierwszą rzeczą jaką zrobił to powołał na swojego doradcę prowincjała jezuitów Manuela Nobregę a następnie postanowił stłumić indiańskie powstania. Do kapitanii Espirito Santo wysłał swojego syna Fernao de Sa i dwustu żołnierzy, gdzie miał uwolnić oblężonych Portugalczyków. Zadanie zostało wykonane ale w trakcie bitwy zginął syn Mem de Sa. Gubernator udał się do kapitanii Ilheus by tam uwolnić oblęzonych Portugalczyków a następnie stoczył bitwę pod Ilheus, pokonując miejscowych Indian. By bronić kapitanii stoczył jeszcze kilkudniową morską bitwę zwaną "bitwą pływaków", z flotą Indiańską złożoną z setek kanoe.</Polish>
	</TEXT>
</Civ4GameText>

=== caveman2cosmos/Caveman2Cosmos/Assets/XML/Text/DancingHoskuld/ExtraDiplomacy/ExtraDiplomacy_CIV4GameText_Events_GStatesman.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_MISSION_STEAL_PLANS2</Tag>
		<English>Bribe</English>
		<French>Corrompre</French>
		<German>A statesman from the %s1_civ has prevented an international incident.</German>
		<Italian>Corrompi</Italian>
		<Spanish>A statesman from the %s1_civ has prevented an international incident.</Spanish>
		<Polish>Łapówka</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MISSION_STEAL_PLANS_HELP2</Tag>
		<English>The [COLOR_UNIT_TEXT]Envoy[COLOR_REVERT] will attempt to bribe a government official, which will reveal all of the target civilization's units.</English>
		<French>L'[COLOR_UNIT_TEXT]espion[COLOR_REVERT] tentera de corrompre un officier d'état et de voler des plans, qui révèlent toutes les unités de la civilisation visée.</French>
		<German>Der [COLOR_UNIT_TEXT]Spion[COLOR_REVERT] versucht, Pläne zu stehlen, die alle Einheiten der gewünschten Zivilisation enthüllen.</German>
		<Italian>La [COLOR_UNIT_TEXT]spia[COLOR_REVERT] tenterà di corrompere un ufficiale nemico per rivelare tutte le unità della civiltà bersaglio.</Italian>
		<Spanish>El [COLOR_UNIT_TEXT]Espía[COLOR_REVERT] intentará robar los planos, que revelarán todas las unidades de la civilización objetivo.</Spanish>
		<Polish>[COLOR_UNIT_TEXT]Poseł[COLOR_REVERT] spróbuje przekupić urzednika rządowego i odkryć rozmieszczenie wrogich jednostek.</Polish>
	</TEXT>
</Civ4GameText>

=== caveman2cosmos/Caveman2Cosmos/Assets/XML/Text/Custom_Leaderheads/AbuBakr/AbuBakr_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>AI_DIPLO_FIRST_CONTACT_LEADER_ABUBAKR_1</Tag>
		<English>What you will need to understand, [CT_NAME], is that anyone who fights on behalf of Allah, when he dies, the first drop of blood that comes out, all of his sins will be forgiven.</English>
		<French>Ce que vous aurez besoin de comprendre, [CT_NAME], est que toute personne qui se bat au nom d'Allah, lorsqu'il meurt, à la première goutte de sang versé, est pardonné de tous ses péchés.</French>
		<Polish>[CT_NAME], musisz zrozumieć, że ten kto walczy w imię Allaha, kiedy umiera, z pierwsza kroplą przelanej krwi, wszystkie jego grzechy zostają odpuszczone.</Polish>
		<Russian>Что вам нужно понять, [CT_NAME], так это то, что любому, сражающемуся от имени Аллаха, после смерти простятся все грехи единственной каплей крови.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_LEADER_ABUBAKR</Tag>
		<English>Abu Bakr</English>
		<Russian>Àáó Áàêð</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_LEADER_ABUBAKR_PEDIA</Tag>
		<English>[H1]Abu Bakr Abdallah ibn Abi Quhafa As-Siddiq[\H1][NEWLINE][BOLD]Caliph of Arabia[\BOLD][NEWLINE][BOLD]Zyl:[\BOLD] c. 573 CE-634[NEWLINE][PARAGRAPH:2][BOLD]Background:[\BOLD][NEWLINE]Abu Bakr Abdallah ibn Abi Quhafa As-Siddiq was an early convert to Islam and a senior companion (Sahaba) of the Islamic prophet Muhammad. Throughout his life, Abu Bakr remained a friend and confidante of Muhammad. Upon Muhammad's death he became the first Muslim ruler (632–634), regarded in Sunni Islam as the first of the Rashidun (righteously guided Caliphs). His caliphate lasted two years and three months, during which time he consolidated the Muslim state. Upon the death of Muhammad, some tribes rebelled, and in return he fought the Ridda wars against these Arab tribes to establish Islamic rule over all of Arabia. He also conquered the lands of Syria and Iraq.[PARAGRAPH:1]Abu Bakr became the Caliph on the 8 June 632 C.E. and he died on 23 August 634 C.E. Though the period of his caliphate covers two years, two months and fifteen days only, his achievements were remarkable. His glorious triumph in Ridda Wars and successful invasions of the two most powerful empires of the time the Sassanid Empire and Byzantine Empire.[PARAGRAPH:1]Abu Bakr had the distinction of being the first Caliph in the history of Islam. He was the first Caliph to nominate a successor. He was the only Caliph in the history of Islam who refunded to the state treasury at the time of his death the entire amount of the allowance that he had drawn during the period of his caliphate.[PARAGRAPH:1]He was the first Muslim ruler to establish Bayt al-mal. He was the first Muslim ruler to establish crown pasture. He was the first Muslim ruler to establish 'Ijtihad'. He has the distinction of purchasing the land for Al-Masjid al-Nabawi. According to Sunni Muslims, in the matter of virtue, Abu Bakr excelled all other Sahaba. Both Abu Bakr and Uthman ibn Affan had relinquished drinking wine even in the time before Islam. He was the foremost genealogist of the Quraysh and the best of them at interpreting dreams after Muhammad according to Ibn Sirin.[PARAGRAPH:1]On 8 August 634, Abu Bakr fell sick, and never recovered. There are two accounts about the sickness of Abu Bakr. One account is that the 8 August 634 was a cold day and when Abu Bakr took a bath, he caught a chill. Another account is that about a year before, along with some other companions, Harith bin Kaladah, and Attab bin Usaid, he had eaten some food which was poisoned, and which was not to affect him for a year. On Monday 23 August 634 Abu Bakr died. The funeral prayer was led by Umar. He was buried the same night by the side of Muhammad's grave in Aisha's house ner Al-Masjid al-Nabawi.</English>
		<Polish>[H1]Abu Bakr Abdallah ibn Abi Quhafa As-Siddiq[\H1][NEWLINE][BOLD]Kalif Arabii[\BOLD][NEWLINE][BOLD]Źył:[\BOLD] ok. 573 CE-634[NEWLINE][PARAGRAPH:2][BOLD]Tło:[\BOLD][NEWLINE]Abu Bakr urodził się w roku 573 w Mekce w plemieniu Kurajszytów. O jego życiu przed nawróceniem się na islam właściwie nic pewnego nie wiadomo, chociaż muzułmańska tradycja twierdzi, że był zamożnym kupcem, co zdają się potwierdzać późniejsze wydarzenia, podczas których miał wielokrotnie wspierać materialnie ubogą gminę muzułmańską podczas pierwszego okresu jej istnienia. Był jednym z pierwszych nawróconych na islam, według niektórych tradycji trzecią osobą po żonie proroka Chadidży i Alim, chociaż większość z nich umieszcza go mniej zaszczytnie wśród kilkunastu pierwszych nawróconych, a jedna z nich powiada nawet: "Było przed nim ponad pięćdziesięciu" aby zaraz dodać: "ale on był najznakomitszy". Stało się to około roku 610. Jego majątek, pozwalający mu np. wykupywać nawróconych na islam niewolników, oraz osobisty autorytet i charyzma, były znaczącym wsparciem w misji Mahometa. Pozycję Abu Bakra jako najbliższego obok Alego towarzysza Proroka wzmocniło w dodatku małżeństwo Mahometa z jego córką, Aiszą, która miała się stać jego ulubioną żoną. O znaczeniu Abu Bakra świadczy choćby fakt powierzenia mu przez Mahometa zadania wygłoszenia chutby podczas hadżdżu w 631 roku.</Polish>
		<Russian>[H1]Абу Бакр Абдаллах ибн Аби Хухафа Ас-Сиддик[\H1][NEWLINE][BOLD]Первый халиф Аравии[\BOLD][NEWLINE][BOLD]Годы жизни: [\BOLD] ок. 573 - 634 гг.[NEWLINE][PARAGRAPH:2][BOLD]Биография:[\BOLD][NEWLINE][TAB]Абу Бакр Абдаллах ибн Аби Кухафа Ас-Сиддик был одним из первых обращенных в ислам и старшим соратником (сахабом) исламского пророка Мухаммеда. На протяжении всей своей жизни Абу Бакр оставался другом и доверенным лицом Мухаммеда. После смерти Мухаммеда он стал первым мусульманским правителем (632–634), которого в суннитском исламе считают первым из Рашидунов (праведных халифов). Его халифат длился два года и три месяца, в течение которых он объединил мусульманское государство. После смерти Мухаммеда некоторые племена восстали, и в ответ он вел войны Ридда против этих арабских племен, чтобы установить исламское правление над всей Аравией. Он также завоевал земли Сирии и Ирака.[PARAGRAPH:1]Абу Бакр стал халифом 8 июня 632 года н. Э. И умер 23 августа 634 года н.э. Хотя период его халифата охватывает только два года, два месяца и пятнадцать дней, его достижения были замечательными. Его славный триумф в войнах Ридда и успешные вторжения в две самые могущественные империи того времени - Сасанидскую империю и Византийскую империю.[PARAGRAPH:1]Абу Бакр имел честь быть первым халифом в истории ислама. Он был первым халифом, назначившим преемника. Он был единственным халифом в истории ислама, который вернул в государственную казну на момент своей смерти всю сумму денежного пособия, полученного им в период своего халифата.[PARAGRAPH:1]Он был первым мусульманским правителем, установившим Байт ал-мал. Он был первым мусульманским правителем, основавшим пастбище короны. Он был первым мусульманским правителем, установившим «иджтихад». Он имеет честь купить землю для Аль-Масджид ан-Набави. По мнению мусульман-суннитов, в вопросе добродетели Абу Бакр превосходил всех других сахабов. И Абу Бакр, и Усман ибн Аффан отказались от вина еще до ислама. Он был ведущим специалистом по генеалогии курайшитов и лучшим из них в толковании снов после Мухаммеда согласно Ибн Сирину.[PARAGRAPH:1]8 августа 634 года Абу Бакр заболел и так и не поправился. Есть два рассказа о болезни Абу Бакра. Согласно одной из версий, 8 августа 634 года был холодным днем, и когда Абу Бакр принял ванну, он простудился. Другой рассказ состоит в том, что около года назад вместе с некоторыми другими товарищами, Харитом бин Каладом и Аттабом бин Усаидом, он съел отравленную пищу, которая не влияла на него в течение года. В понедельник 23 августа 634 года Абу Бакр скончался. Погребальную молитву возглавил Умар. Он был похоронен в ту же ночь рядом с могилой Мухаммеда в доме Аиши в Аль-Масджид ан-Набави.</Russian>
	</TEXT>
</Civ4GameText>

=== caveman2cosmos/Caveman2Cosmos/Assets/XML/Text/Custom_Leaderheads/Nefertiti/Nefertiti_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>AI_DIPLO_FIRST_CONTACT_LEADER_NEFERTITI_1</Tag>
		<English>I am [OUR_NAME] of the great and glorious [OUR_EMPIRE]! Let us sit in peace with one another.</English>
		<French>Je suis [OUR_NAME] du grand et glorieux [OUR_EMPIRE]! Asseyons-nous en paix les uns avec les autres.</French>
		<Polish>Jestem [OUR_NAME], z wielkiego i wspaniałego [OUR_EMPIRE]! Usiądźmy w pokoju i porozmawiajmy.</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_LEADER_NEFERTITI</Tag>
		<English>Nefertiti</English>
		<French>Néfertiti</French>
		<Polish>Nefretete</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_LEADER_NEFERTITI_PEDIA</Tag>
		<English>[H1]Nefertiti[\H1][NEWLINE][BOLD]Great Royal Wife of Akhenatent[\BOLD][NEWLINE][BOLD]Dates:[\BOLD] c. 1370 - c. 1330 BC[NEWLINE][PARAGRAPH:1][BOLD]Background:[\BOLD][NEWLINE]Nefertiti was the Great Royal Wife (chief consort) of the Egyptian Pharaoh Akhenaten. Nefertiti and her husband were known for changing Egypt's religion from a polytheistic religion to a henotheistic religion. They revered only one god, Aten, the sun disc. This was not strictly monotheism, as they did not deny the existence of other gods. She had many titles; for example, at Karnak there are inscriptions that read «Heiress, Great of Favours, Possessed of Charm, Exuding Happiness, Mistress of Sweetness, beloved one, soothing the king's heart in his house, soft-spoken in all, Mistress of Upper and Lower Egypt, Great King's Wife, whom he loves, Lady of the Two Lands, Nefertiti».[PARAGRAPH:1]She was made famous by her bust, now in Berlin's Altes Museum, shown to the right. The bust is one of the most copied works of ancient Egypt. It was attributed to the sculptor Thutmose, and it was thought to have been found in his workshop. The bust itself is notable for exemplifying the understanding Ancient Egyptians had regarding realistic facial proportions. Recently, it has been suggested by Swiss art historian Henri Stierlin that the bust is a copy dating from 1912.[PARAGRAPH:1]Some scholars believe that Nefertiti ruled briefly after her husband's death and before the accession of Tutankhamun as Smenkhkare, although this identification is a matter of ongoing debate. During Akhenaten's reign (and perhaps after) Nefertiti enjoyed unprecedented power, and by the twelfth year of his reign, there is evidence that she may have been elevated to the status of co-regent: equal in status to the pharaoh himself. She was often depicted on temple walls the same size as the king, signifying her importance, and shown worshiping the Aten alone. Perhaps most impressively, Nefertiti is shown on a relief from the temple at Amarna which is now in the MFA in Boston, smiting a foreign enemy with a mace before the Aten. Such depictions had traditionally been reserved for the pharaoh alone, and yet Nefertiti was depicted as such.[PARAGRAPH:1]The Coregency Stela may show her as a co-regent with her husband, who possibly ruled after his death. It is thought by some scholars that Nefertiti changed her name, first to Ankhkheperure Neferneferuaten and later to Ankhkheperure Smenkhkare and that she enjoyed a brief sole rule under the latter name. it is also believed that, as her husband's co-regent and successor she might have attempted to reconcile the Atenist and Traditional religions Nefertiti would have prepared for her death and for the succession of her daughter, now named Ankhsenamun, and her stepson, Tutankhamun. They would have been educated in the traditional way, worshiping the old gods. This theory has Neferneferuaten dying after two years of kingship and was then succeeded by Tutankhamun, thought to have been a son of Akhenaten. He married Nefertiti's daughter Ankhesenpaaten. The royal couple were young and inexperienced, by any estimation of their age, and Ankhesenpaaten bore two stillborn (and premature) daughters whose mummies were found by Howard Carter in Tutankhamen's tomb. Some theories believe that Nefertiti was still alive and held influence on the younger royals.[PARAGRAPH:1]Nefertiti's place as an icon in popular culture is secure as she has become somewhat of a celebrity. After Cleopatra she is the second most famous "Queen" of Egypt in the Western imagination and influenced through photographs that changed standards of feminine beauty of the 20th century, and is often referred to as "the most beautiful woman in the world".</English>
		<Polish>[H1]Nefretete[\H1][NEWLINE][BOLD]Wielka Żona Króla Akhenatent[\BOLD][NEWLINE][BOLD]Daty:[\BOLD] ok. 1370 - ok. 1330 p.n.e[NEWLINE][PARAGRAPH:1][BOLD]Tło:[\BOLD][NEWLINE]Żona faraona Echnatona z XVIII dynastii ( Amenhotep IV/Amenhatpa IV). Prawdopodobnie imię jej wymawiało się jako Nafteta. Pochodzenie Nefertiti nie jest do końca jasne. Przedstawia się teorię jakoby była księżniczką mitannijską - co tłumaczyłoby jej imię, utożsamia się ją też z Taduhepą. Często przyjmuje się także, iż była córką doradcy dworu Aj, który wstąpił na tron po śmierci Tutanchamona. Była ukochaną żoną Echnatona, z którym miała 6 córek: Meritaton, Maketaton, Anchesenpaaton, Neferneferuaton-Taszerit, Neferneferure i Setepenre. Prawdopodobnie została wyniesiona na tron jako współregent i przybrała imię Neferneferuaton ("Nadzwyczajna piękność Atona"). Jako jedyna królowa w historii Egiptu jest przedstawiana na nielicznych zachowanych płaskorzeźbach w pozach zarezerwowanych dla faraonów, np. zwyciężania lub upokarzania wrogów Egiptu. Była także macochą Tutanchamona, syna ze związku Echnatona i jego drugorzędnej żony Kiji. Stawiane są także hipotezy, że po śmierci swego męża objęła tron jako Anchcheperure Semenchkare.</Polish>
	</TEXT>
</Civ4GameText>

=== caveman2cosmos/Caveman2Cosmos/Assets/Modules/My_Mods (unloaded)/_Animal_Template/AT_CIV4GameTxt.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CROW_MYTH</Tag>
		<English>Myth - Crow</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CROW_MYTH_EFFECT</Tag>
		<English>Myth Effect - Crow</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CROW_STORIES</Tag>
		<English>Stories - Crow</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CROW_STORIES_EFFECT</Tag>
		<English>Stories Effect - Crow</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_CROW_STORY</Tag>
		<English>Story - Crow</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_CROW</Tag>
		<English>Crow</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_CROW_PEDIA</Tag>
		<English>Information on Crow
Graphics Source:
		</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_SUBDUED_CROW</Tag>
		<English>Subdued Crow</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_SUBDUED_CROW_HELP</Tag>
		<English>[COLOR_HIGHLIGHT_TEXT]Build[COLOR_REVERT] Myth, Story and Stories - Crow and Sea Birds[NEWLINE][ICON_BULLET]Bird Cage and Enclosure[NEWLINE][ICON_BULLET]Feather Worker</English>
	</TEXT>
</Civ4GameText>
